#!/usr/bin/env python3
"""Regenerate the self-hosted webfonts in public/fonts/ and src/styles/fonts.css.

The site used to load these from fonts.googleapis.com. That cost a render-blocking
stylesheet on a third-party origin, which then discovered six woff2 files on a
*second* third-party origin — a three-level critical chain in front of a text LCP.
Serving the identical woff2 files from our own origin collapses that chain.

The files this downloads are the exact ones Google serves, so rendering does not
change. Only the latin and latin-ext subsets are kept: this site is EN + ES, and
Google's cyrillic/greek/vietnamese subsets were never requested.

Google returns one variable font for all three Inter weights, so identical files
are stored once and referenced by all the weights that share them.

Run from the repo root:  python3 scripts/fetch-fonts.py
"""

import hashlib
import os
import re
import urllib.request

# Keep in sync with the families actually used in src/styles/global.css
# (--cond, --mono, --body).
FONT_CSS_URL = (
    "https://fonts.googleapis.com/css2"
    "?family=Barlow+Condensed:wght@400;600;700;900"
    "&family=IBM+Plex+Mono:wght@400;600"
    "&family=Inter:wght@400;500;600"
    "&display=swap"
)

# Asking as a modern browser is what makes Google serve woff2 rather than ttf.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

KEEP_SUBSETS = {"latin", "latin-ext"}

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(REPO, "public", "fonts")
CSS_OUT = os.path.join(REPO, "src", "styles", "fonts.css")

HEADER = """/* Self-hosted webfonts — generated by scripts/fetch-fonts.py. Do not hand-edit.

   These are the exact woff2 files Google Fonts serves, so rendering is
   unchanged from the old CDN setup. Serving them from our own origin removes a
   render-blocking third-party stylesheet and the second-origin font requests it
   discovered, which together sat in front of this site's text LCP.

   Only latin and latin-ext are included; the site is EN + ES. unicode-range is
   preserved, so latin-ext is fetched only if a page actually uses those glyphs.

   This file is @imported by BaseLayout alongside global.css, so it is bundled
   into the same stylesheet and costs no additional request. */
"""


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30
    ).read()


def main() -> None:
    css = fetch(FONT_CSS_URL).decode("utf-8")
    blocks = re.findall(r"/\*\s*([a-z\-]+)\s*\*/\s*@font-face\s*\{(.*?)\}", css, re.S)

    os.makedirs(FONT_DIR, exist_ok=True)
    for stale in os.listdir(FONT_DIR):
        if stale.endswith(".woff2"):
            os.remove(os.path.join(FONT_DIR, stale))

    by_hash: dict[str, str] = {}
    faces = []
    total = 0

    for subset, body in blocks:
        if subset not in KEEP_SUBSETS:
            continue
        family = re.search(r"font-family:\s*'([^']+)'", body).group(1)
        weight = re.search(r"font-weight:\s*(\d+)", body).group(1)
        src_url = re.search(r"src:\s*url\(([^)]+)\)", body).group(1)
        urange = re.search(r"unicode-range:\s*([^;]+);", body).group(1).strip()

        data = fetch(src_url)
        digest = hashlib.md5(data).hexdigest()

        if digest in by_hash:
            # Same bytes as a weight already written (Inter ships one variable
            # font for 400/500/600). Reference the existing file instead of
            # storing a duplicate.
            filename = by_hash[digest]
        else:
            slug = family.lower().replace(" ", "-")
            filename = f"{slug}-{weight}-{subset}.woff2"
            with open(os.path.join(FONT_DIR, filename), "wb") as fh:
                fh.write(data)
            by_hash[digest] = filename
            total += len(data)
            print(f"  {filename:<40} {len(data):>7,} B")

        faces.append((family, weight, filename, urange))

    lines = [HEADER]
    for family, weight, filename, urange in faces:
        lines.append(
            "@font-face {\n"
            f"  font-family: '{family}';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('/fonts/{filename}') format('woff2');\n"
            f"  unicode-range: {urange};\n"
            "}"
        )

    with open(CSS_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    print(f"\n{len(faces)} @font-face rules -> {len(by_hash)} files, {total:,} B")


if __name__ == "__main__":
    main()
