#!/usr/bin/env python3
"""Assembles finished TikTok videos for RigFloorHQ from the existing frame
images (social/tiktok/*-frameN.png, generated by make-tiktok-frames.ps1) plus
narration and burned captions generated here.

Narration comes from edge-tts (free, local, no API key) rather than TikTok's
own built-in TTS, because upload now goes through Metricool instead of
TikTok's native composer -- so TikTok's own "turn auto-captions on" step
never runs. Captions are burned in here instead, timed to edge-tts's own
word-boundary timestamps rather than a separate speech-to-text pass, since we
already know exactly what's being said (we generated it).

Scripts below are copies of social/README.md's five spoken videos (01-05).
Keep them in sync with the README if either changes. Videos 06-08 are
screen-recording bookends, not narrated slideshows -- record those manually.

Requires: ffmpeg on PATH, `pip install edge-tts`.

Run:
  python scripts/make-tiktok-videos.py            all five videos
  python scripts/make-tiktok-videos.py 01 05       just these ids
"""
import asyncio
import subprocess
import sys
from pathlib import Path

import edge_tts

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
OUT = REPO / "social" / "tiktok"

VOICE = "en-US-ChristopherNeural"
FONT_SIZE = 52
MARGIN_V = 520          # keeps burned captions inside the frames' safe zone
HOOK_S = 2.0            # fixed length of frame 1 (the hook) before frame 2 cuts in
TAIL_PAD_S = 0.6        # trailing silence held after the last spoken word
CTA_HOLD_S = 3.0        # hold time for a trailing frame with no narration of its own (pure CTA card)

VIDEOS = {
    "01": {
        "id": "01-differential-sticking",
        # One entry per frame -- joined back into the same script for
        # narration, but kept separate so each frame's on-screen cut can be
        # timed to when its own line actually starts being said instead of
        # splitting the remaining runtime evenly across frames.
        "segments": [
            "Your drill string is stuck. The one thing you should not do "
            "is pull harder.",
            "Differential sticking is pressure holding the pipe against "
            "the wall. The force is the pressure difference multiplied by "
            "the contact area, and tension reduces neither of them.",
            "Worse, in a deviated hole pulling presses the string harder "
            "into the wall, which increases the contact area.",
            "You do not out-pull it. You lower the pressure.",
        ],
    },
    "02": {
        "id": "02-hole-cleaning",
        "segments": [
            "Everyone assumes horizontal wells are the hardest to clean. "
            "They are not.",
            "Past about fifty degrees, cuttings settle onto the low side "
            "and leave the flow entirely, they stop being carried and "
            "start accumulating. But near horizontal, those beds mostly "
            "sit still.",
            "Between forty five and sixty degrees they form and have a "
            "slope to slide down, so they avalanche.",
            "The dangerous angle is the middle one.",
        ],
    },
    "03": {
        "id": "03-neutral-point",
        "segments": [
            "Weight on bit does not come from pushing down from surface. "
            "It comes from letting part of the string's own weight rest "
            "on the bit.",
            "Drill collars are thick walled and built for compression. "
            "Drill pipe is thin walled and built for tension.",
            "The boundary is the neutral point, and it has to stay inside "
            "the collars. Put drill pipe into compression and it buckles, "
            "fatigues at the tool joints, and eventually parts.",
            "",  # frame 4 is a pure CTA card -- no narration of its own
        ],
    },
    "04": {
        "id": "04-6g-welding",
        "script": "There is one welding test worth having, and the rest are "
                   "included. Welder qualification is by position, not by how "
                   "the weld looks. One G rotates the pipe, so you never leave "
                   "flat. Five G is fixed horizontal. Six G is fixed at forty "
                   "five degrees, every position in a single weld, with no "
                   "comfortable place to start. Pass six G and you are "
                   "qualified for everything below it. On a rig you cannot "
                   "rotate a mud line to suit yourself.",
    },
    "05": {
        "id": "05-torque-and-drag",
        "segments": [
            "By the time torque looks high, you have been in trouble "
            "for hours.",
            "A torque figure means nothing on its own, it depends on "
            "depth, angle, mud and hole size.",
            "What carries the information is the gap between what the "
            "model predicted and what the string actually did. That gap "
            "opens several connections before the number ever looks "
            "alarming.",
            "Watch the divergence, not the value.",
        ],
    },
}


async def synthesize(text: str, out_wav: Path) -> list[dict]:
    """Writes narration audio, returns word-boundary timing (seconds)."""
    communicate = edge_tts.Communicate(text, VOICE, boundary="WordBoundary")
    words = []
    with open(out_wav, "wb") as f:
        async for chunk in communicate.stream():
            if chunk["type"] == "audio":
                f.write(chunk["data"])
            elif chunk["type"] == "WordBoundary":
                words.append({
                    "text": chunk["text"],
                    "start": chunk["offset"] / 1e7,
                    "end": (chunk["offset"] + chunk["duration"]) / 1e7,
                })
    return words


def srt_timestamp(t: float) -> str:
    ms = round(t * 1000)
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f"{h:02}:{m:02}:{s:02},{ms:03}"


def build_srt(words: list[dict], out_srt: Path, chunk_size: int = 4):
    lines = []
    idx = 1
    for i in range(0, len(words), chunk_size):
        group = words[i:i + chunk_size]
        start, end = group[0]["start"], group[-1]["end"]
        text = " ".join(w["text"] for w in group)
        lines.append(f"{idx}\n{srt_timestamp(start)} --> {srt_timestamp(end)}\n{text}\n")
        idx += 1
    out_srt.write_text("\n".join(lines), encoding="utf-8")


def ass_timestamp(t: float) -> str:
    cs = round(t * 100)
    h, cs = divmod(cs, 360000)
    m, cs = divmod(cs, 6000)
    s, cs = divmod(cs, 100)
    return f"{h:01}:{m:02}:{s:02}.{cs:02}"


# Burning captions via the `subtitles` filter's force_style was silently
# placing them off-frame: ffmpeg's SRT-to-ASS conversion has no resolution
# info to go on, so libass falls back to its default 384x288 script
# canvas, and force_style's FontSize/MarginV get interpreted in THAT
# canvas's units, not the real 1080x1920 output -- MarginV=520 in a
# 288-tall canvas pushed every caption above the top of the frame,
# invisible in every video despite every prior sync/frame-rate check
# passing (none of them ever confirmed caption *text* was on screen).
# Writing a real .ass file with PlayResX/PlayResY set to the actual
# output size makes every style value a literal pixel value -- no hidden
# canvas, no guessing a scale factor. See [[RigFloorHQ Social Posting]].
def ass_header() -> str:
    return (
        "[Script Info]\n"
        "ScriptType: v4.00+\n"
        "PlayResX: 1080\n"
        "PlayResY: 1920\n"
        "\n"
        "[V4+ Styles]\n"
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, "
        "OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, "
        "ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, "
        "Alignment, MarginL, MarginR, MarginV, Encoding\n"
        f"Style: Default,Arial,{FONT_SIZE},&H00FFFFFF,&H00FFFFFF,&H00101010,"
        "&H00000000,-1,0,0,0,100,100,0,0,1,3,0,2,60,60,"
        f"{MARGIN_V},1\n"
        "\n"
        "[Events]\n"
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, "
        "Effect, Text\n"
    )


def build_ass(words: list[dict], out_ass: Path, chunk_size: int = 4):
    lines = [ass_header()]
    for i in range(0, len(words), chunk_size):
        group = words[i:i + chunk_size]
        start, end = group[0]["start"], group[-1]["end"]
        text = " ".join(w["text"] for w in group)
        lines.append(
            f"Dialogue: 0,{ass_timestamp(start)},{ass_timestamp(end)},"
            f"Default,,0,0,0,,{text}\n"
        )
    out_ass.write_text("".join(lines), encoding="utf-8")


def srt_to_ass(srt_path: Path, out_ass: Path):
    """For videos 06-08: their .srt was generated by an earlier one-off
    narration pass that didn't keep the per-word timing data around, so
    there's no `words` list to rebuild from -- just re-wrap the existing
    .srt's own group timestamps/text into the same corrected .ass header
    used by build_ass() above. Same fix, same reason, see build_ass's
    comment."""
    raw = srt_path.read_text(encoding="utf-8")
    lines = [ass_header()]
    for block in raw.strip().split("\n\n"):
        rows = block.strip().splitlines()
        if len(rows) < 3:
            continue
        start_str, end_str = rows[1].split(" --> ")
        text = " ".join(rows[2:])

        def to_seconds(ts: str) -> float:
            h, m, rest = ts.split(":")
            s, ms = rest.split(",")
            return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000

        start, end = to_seconds(start_str), to_seconds(end_str)
        lines.append(
            f"Dialogue: 0,{ass_timestamp(start)},{ass_timestamp(end)},"
            f"Default,,0,0,0,,{text}\n"
        )
    out_ass.write_text("".join(lines), encoding="utf-8")


def frame_durations_from_segments(segments: list[str], words: list[dict]) -> list[float]:
    """Times every frame -- including frame 1 -- to the word-boundary
    timestamp where its own segment actually starts, instead of splitting
    the remaining runtime evenly (which drifted the on-screen headline
    further behind the narration with every frame cut) or fixing frame 1's
    length to a flat hook duration (which showed frame 2's headline for
    several seconds before its own line was ever spoken, e.g. video 02's
    "Past 50 degrees" card sitting up during the "...hardest to clean. They
    are not." tail of frame 1's own line). See [[RigFloorHQ Social Posting]],
    2026-09-05 desync incidents."""
    assert all(segments[i] for i in range(len(segments) - 1)), (
        "only the last segment may be empty (a trailing CTA card with no "
        "narration of its own)"
    )
    word_counts = [len(seg.split()) for seg in segments]
    cum = [0]
    for c in word_counts:
        cum.append(cum[-1] + c)

    starts = [0.0] * len(segments)
    for i in range(1, len(segments)):
        starts[i] = words[cum[i]]["start"] if word_counts[i] else None

    last_word_end = words[-1]["end"]
    if starts[-1] is None:
        starts[-1] = last_word_end + 0.3
        total = starts[-1] + CTA_HOLD_S
    else:
        total = last_word_end + TAIL_PAD_S

    return [b - a for a, b in zip(starts, starts[1:])] + [total - starts[-1]]


def build_video(vid: dict):
    tag = vid["id"]
    frames = sorted(OUT.glob(f"{tag}-frame*.png"))
    if not frames:
        print(f"  SKIP {tag}: no frames found -- run make-tiktok-frames.ps1 first")
        return
    wav = OUT / f"{tag}.wav"
    srt = OUT / f"{tag}.srt"
    ass = OUT / f"{tag}.ass"
    mp4 = OUT / f"{tag}.mp4"

    segments = vid.get("segments")
    script = " ".join(segments) if segments else vid["script"]

    print(f"  {tag}: synthesizing narration ({VOICE})...")
    words = asyncio.run(synthesize(script, wav))
    build_srt(words, srt)  # kept for reference/other platforms, not burned in
    build_ass(words, ass)

    if segments and words and len(segments) == len(frames):
        durations = frame_durations_from_segments(segments, words)
    else:
        # Legacy fallback for any video with a flat "script" instead of
        # per-frame "segments" -- splits the remaining runtime evenly.
        duration = words[-1]["end"] + TAIL_PAD_S if words else 15.0
        n_rest = len(frames) - 1
        rest_each = max(1.5, (duration - HOOK_S) / n_rest) if n_rest else duration
        durations = [HOOK_S] + [rest_each] * n_rest

    total_duration = sum(durations)

    concat_txt = OUT / f"{tag}-concat.txt"
    with open(concat_txt, "w", encoding="utf-8") as f:
        for frame, d in zip(frames, durations):
            f.write(f"file '{frame.name}'\nduration {d}\n")
        f.write(f"file '{frames[-1].name}'\n")  # ffmpeg concat quirk: repeat last entry

    vf = f"ass={ass.name}"

    print(f"  {tag}: assembling video...")
    subprocess.run([
        "ffmpeg", "-y",
        "-f", "concat", "-safe", "0", "-i", concat_txt.name,
        "-i", wav.name,
        "-af", "apad",
        "-vf", f"scale=1080:1920,fps=30,{vf}",
        "-c:v", "libx264", "-pix_fmt", "yuv420p",
        "-c:a", "aac", "-t", str(total_duration),
        mp4.name,
    ], cwd=OUT, check=True)
    concat_txt.unlink()
    verify_frame_rate(mp4)
    print(f"  DONE -> {mp4.relative_to(REPO)}")


def verify_frame_rate(mp4: Path, min_fps: float = 23.0, max_fps: float = 60.0):
    """TikTok rejects uploads outside 23-60fps. The concat demuxer only
    re-times still frames unless the output filter forces a real frame
    rate (fps=30 above) -- without it ffmpeg emits one frame per still,
    which reports as a fraction of an fps. Fail loud here instead of
    finding out at upload time."""
    result = subprocess.run([
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-count_frames", "-show_entries", "stream=nb_read_frames",
        "-of", "csv=p=0", str(mp4),
    ], capture_output=True, text=True, check=True)
    frame_count = int(result.stdout.strip())

    result = subprocess.run([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "csv=p=0", str(mp4),
    ], capture_output=True, text=True, check=True)
    duration_s = float(result.stdout.strip())

    actual_fps = frame_count / duration_s
    if not (min_fps <= actual_fps <= max_fps):
        raise RuntimeError(
            f"{mp4.name}: real frame rate {actual_fps:.1f}fps is outside "
            f"TikTok's {min_fps}-{max_fps}fps range ({frame_count} frames / "
            f"{duration_s:.1f}s) -- fix the ffmpeg filter chain before "
            f"treating this file as ready to upload."
        )


def main():
    ids = sys.argv[1:] or list(VIDEOS)
    OUT.mkdir(parents=True, exist_ok=True)
    for vid_id in ids:
        v = VIDEOS.get(vid_id)
        if not v:
            print(f"unknown video id: {vid_id} (known: {', '.join(VIDEOS)})")
            continue
        build_video(v)


if __name__ == "__main__":
    main()
